toi:
  telescopes: ["wk06","zb08","jk15"]
  nats_host: nats.oca.lan
  nats_port: 4222

  mark_saturated_stars: True
  log_display_h: 8

  show_sat_stars: True


wk06:
  tel_directory: /data/fits/wk06/
  tel_ob_list: /data/misc/synced/objects_list/
  flat_log_files: /Logs/wk06_flats_log.txt
  object_catalog: ./object_catalog.txt

  light_ip: 192.168.7.217
  overhead: 15
  showRotator: False

zb08:
  tel_directory: /data/fits/zb08/
  tel_ob_list: /data/misc/synced/objects_list/
  flat_log_files: /Logs/zb08_flats_log.txt
  object_catalog: ./object_catalog.txt

  light_ip: 192.168.7.216
  overhead: 15
  showRotator: True

jk15:
  tel_directory: /data/fits/jk15/
  tel_ob_list: /data/misc/synced/objects_list/
  flat_log_files: /Logs/jk15_flats_log.txt
  object_catalog: ./object_catalog.txt

  light_ip: 192.168.7.218
  overhead: 25
  showRotator: True


ctc:
  ctc_base_folder: /data/misc/cycle_time_calc
  rm_modes_mhz: {
    "zb08": [5, 3, 1, 0.05],
    "jk15": [4, 2, 1, 1, 0.1, 0.1],
    "wk06": [5, 3, 1, 0.05],
    "dev": [1, 1, 1, 1, 1, 1, 1],
    "sim": [1, 1, 1, 1, 1, 1, 1],
    "default": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
